### ISSUE TITLE
navigation bar disappears when subroute is opened

### ISSUE THREAD

**Issue by fondraco** [dhafinrayhan/dummymart#65]
This is mostly visible on iOS slide animation when transitioning from shellroute to the subroute. Somehow the navigation bar disappears and reappears after fully closing the subroute again.

How can this be solved?

**Comment by dhafinrayhan** [comment]
Thanks for opening the issue! This issue happens because all routes are built using the same builder that wraps the page in a `ScaffoldWithNavigation`, which checks if the current path from the router is one of the "navigation items" or not. When transitioning to a subroute, the current path is immediately changed to the subroute path but the transition is not immediate, causing the navigation bar to disappear without harmony with the transition.

I opened a PR trying to solve this by wrapping only the "navigation items" with the `ScaffoldWithNavigation` widget, and the rest of the routes use regular `Scaffold`. Please let me know if you have any thoughts on this!
